/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ContactInquiry {
  'id' : bigint,
  'name' : string,
  'submittedAt' : Time,
  'email' : string,
  'message' : string,
  'phone' : string,
}
export interface DemoBooking {
  'id' : bigint,
  'city' : string,
  'name' : string,
  'createdAt' : Time,
  'email' : string,
  'message' : string,
  'preferredDate' : Time,
  'mobile' : string,
  'organization' : string,
}
export interface InsightContent {
  'id' : bigint,
  'title' : string,
  'content' : string,
  'author' : string,
  'summary' : string,
  'publicationDate' : Time,
  'category' : string,
}
export interface NetworkJoinRequest {
  'id' : bigint,
  'status' : string,
  'organizationName' : string,
  'organizationType' : string,
  'name' : string,
  'submittedAt' : Time,
  'message' : string,
  'contactDetails' : string,
}
export interface PageAnalytics {
  'viewCount' : bigint,
  'engagementScore' : number,
  'pageSection' : string,
}
export type Time = bigint;
export interface UserProfile {
  'name' : string,
  'email' : string,
  'organization' : [] | [string],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addInsightContent' : ActorMethod<
    [string, string, string, string, string, Time],
    undefined
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getAllContactInquiries' : ActorMethod<[], Array<ContactInquiry>>,
  'getAllDemoBookings' : ActorMethod<[], Array<DemoBooking>>,
  'getAllInsights' : ActorMethod<[], Array<InsightContent>>,
  'getAllNetworkRequests' : ActorMethod<[], Array<NetworkJoinRequest>>,
  'getAllPageAnalytics' : ActorMethod<[], Array<PageAnalytics>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getInsightsByCategory' : ActorMethod<[string], Array<InsightContent>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'recordPageView' : ActorMethod<[string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitContactInquiry' : ActorMethod<
    [string, string, string, string],
    undefined
  >,
  'submitDemoBooking' : ActorMethod<
    [string, string, string, string, string, string, Time],
    undefined
  >,
  'submitNetworkJoinRequest' : ActorMethod<
    [string, string, string, string, string],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];