/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ContactInquiry = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'submittedAt' : Time,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'phone' : IDL.Text,
});
export const DemoBooking = IDL.Record({
  'id' : IDL.Nat,
  'city' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : Time,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'preferredDate' : Time,
  'mobile' : IDL.Text,
  'organization' : IDL.Text,
});
export const InsightContent = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'author' : IDL.Text,
  'summary' : IDL.Text,
  'publicationDate' : Time,
  'category' : IDL.Text,
});
export const NetworkJoinRequest = IDL.Record({
  'id' : IDL.Nat,
  'status' : IDL.Text,
  'organizationName' : IDL.Text,
  'organizationType' : IDL.Text,
  'name' : IDL.Text,
  'submittedAt' : Time,
  'message' : IDL.Text,
  'contactDetails' : IDL.Text,
});
export const PageAnalytics = IDL.Record({
  'viewCount' : IDL.Nat,
  'engagementScore' : IDL.Float64,
  'pageSection' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'organization' : IDL.Opt(IDL.Text),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addInsightContent' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, Time],
      [],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getAllContactInquiries' : IDL.Func([], [IDL.Vec(ContactInquiry)], ['query']),
  'getAllDemoBookings' : IDL.Func([], [IDL.Vec(DemoBooking)], ['query']),
  'getAllInsights' : IDL.Func([], [IDL.Vec(InsightContent)], ['query']),
  'getAllNetworkRequests' : IDL.Func(
      [],
      [IDL.Vec(NetworkJoinRequest)],
      ['query'],
    ),
  'getAllPageAnalytics' : IDL.Func([], [IDL.Vec(PageAnalytics)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getInsightsByCategory' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(InsightContent)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'recordPageView' : IDL.Func([IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitContactInquiry' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'submitDemoBooking' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, Time],
      [],
      [],
    ),
  'submitNetworkJoinRequest' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ContactInquiry = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'submittedAt' : Time,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'phone' : IDL.Text,
  });
  const DemoBooking = IDL.Record({
    'id' : IDL.Nat,
    'city' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : Time,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'preferredDate' : Time,
    'mobile' : IDL.Text,
    'organization' : IDL.Text,
  });
  const InsightContent = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'author' : IDL.Text,
    'summary' : IDL.Text,
    'publicationDate' : Time,
    'category' : IDL.Text,
  });
  const NetworkJoinRequest = IDL.Record({
    'id' : IDL.Nat,
    'status' : IDL.Text,
    'organizationName' : IDL.Text,
    'organizationType' : IDL.Text,
    'name' : IDL.Text,
    'submittedAt' : Time,
    'message' : IDL.Text,
    'contactDetails' : IDL.Text,
  });
  const PageAnalytics = IDL.Record({
    'viewCount' : IDL.Nat,
    'engagementScore' : IDL.Float64,
    'pageSection' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'organization' : IDL.Opt(IDL.Text),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addInsightContent' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, Time],
        [],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getAllContactInquiries' : IDL.Func(
        [],
        [IDL.Vec(ContactInquiry)],
        ['query'],
      ),
    'getAllDemoBookings' : IDL.Func([], [IDL.Vec(DemoBooking)], ['query']),
    'getAllInsights' : IDL.Func([], [IDL.Vec(InsightContent)], ['query']),
    'getAllNetworkRequests' : IDL.Func(
        [],
        [IDL.Vec(NetworkJoinRequest)],
        ['query'],
      ),
    'getAllPageAnalytics' : IDL.Func([], [IDL.Vec(PageAnalytics)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getInsightsByCategory' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(InsightContent)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'recordPageView' : IDL.Func([IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitContactInquiry' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'submitDemoBooking' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, Time],
        [],
        [],
      ),
    'submitNetworkJoinRequest' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };